apiVersion: v1
kind: Secret
metadata:
  name: wordpress-mysql
  namespace: wordpress
type: Opaque
stringData:
  mysql-database: wordpress
  mysql-user: wordpress
  mysql-password: <wordpress_mysql_password>
  mysql-root-password: <wordpress_mysql_root_password>
